dsddd

diff --git a/deploy_manager b/deploy_manager
--- a/deploy_manager
+++ b/deploy_manager
@@ -54,6 +54,11 @@ else
   exit 1
 fi
 
+if [ $? -ne 0 ]; then
+  echo "JavaScript script failed"
+  exit 1
+fi
+
 if [[ $NETWORK == "mainnet" || $NETWORK == "goerli" ]]; then
 
   # Update .openzeppelin metadata
