dsddd

diff --git a/deploy_manager b/deploy_manager
--- a/deploy_manager
+++ b/deploy_manager
@@ -35,36 +35,38 @@ select BRANCH in $BRANCHES; do
   fi
 done
 
+run_command() {
+  if ! "$@" > /dev/null 2>&1; then
+    echo "$1 command failed"
+    exit 1
+  fi
+}
+
 # Checkout the selected branch and install npm dependencies
-git checkout $BRANCH
-npm ci -q --no-progress
+run_command git checkout $BRANCH
+run_command npm ci -q --no-progress
 
 # Compile project
-npx hardhat compile --force
+run_command npx hardhat compile --force
 
 source ./tag-release -b "$BRANCH" -t "$VERSIONTYPE" -n
 
 if [ "$ACTION" == "deploy" ]; then
   # Run script to deploy the contracts
-  npx hardhat --network "$NETWORK" deploy:contracts --tag "$TAGVERSION"
+  run_command npx hardhat --network "$NETWORK" deploy:contracts --tag "$TAGVERSION"
 elif [ "$ACTION" == "upgrade" ]; then
-  npx hardhat --network "$NETWORK" upgrade:Lock --tag "$TAGVERSION"
+  run_command npx hardhat --network "$NETWORK" upgrade:Lock --tag "$TAGVERSION"
 else
   echo "-- ERROR: Wrong ACTION value. Possible values: [deploy | upgrade]"
-  exit 1
-fi
-
-if [ $? -ne 0 ]; then
-  echo "JavaScript script failed"
   exit 1
 fi
 
 if [[ $NETWORK == "mainnet" || $NETWORK == "goerli" ]]; then
 
   # Update .openzeppelin metadata
-  git add .openzeppelin/"$NETWORK".json
-  git commit -m "Update .openzeppelin folder"
-  git push -u origin $branch
+  run_command git add .openzeppelin/"$NETWORK".json
+  run_command git commit -m "Update .openzeppelin folder"
+  run_command git push -u origin $branch
 
   if [[ $BRANCH == "stage" || $BRANCH == "main" ]]; then
     source ./tag-release -b "$BRANCH" -t "$VERSIONTYPE"
@@ -73,15 +75,15 @@ if [[ $NETWORK == "mainnet" || $NETWORK == "goerli" ]]; then
     ABIDIR="docs/$NETWORK/abi/untagged"
   fi
 
-  git checkout gh-pages
+  run_command git checkout gh-pages
 
   # Publish the ABI to a specific GitHub Pages location
   mkdir -p $ABIDIR
   cp abi/*.json $ABIDIR
 
-  git add $ABIDIR
-  git commit -m "Publish ABI for deployment to $NETWORK"
-  git push -u -f origin gh-pages
+  run_command git add $ABIDIR
+  run_command git commit -m "Publish ABI for deployment to $NETWORK"
+  run_command git push -u -f origin gh-pages
 fi
 
-git checkout $CURRENT_BRANCH
+run_command git checkout $CURRENT_BRANCH
